
DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS GRADE;
DROP TABLE IF EXISTS CONTACT;

create table grade(grade_id bigint(20) PRIMARY KEY, grade_name varchar(255));

insert into grade (grade_id,grade_name) values (1,'FIRST');
insert into grade (grade_id,grade_name) values (2,'SECOND');
insert into grade (grade_id,grade_name) values (3,'THIRD');
insert into grade (grade_id,grade_name) values (4,'FOURTH');

CREATE TABLE CONTACT(
	CONTACT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	BUILDING VARCHAR(255),
	STREET VARCHAR(255),
	AREA VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE student (
	STUDENT_ID bigint(20) NOT NULL AUTO_INCREMENT,
	DATE_OF_BIRTH date DEFAULT NULL,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) DEFAULT NULL,
	MIDDLE_NAME varchar(255) DEFAULT NULL,
	GRADE_ID bigint(20) DEFAULT NULL,
	CONTACT_ID BIGINT(20) DEFAULT NULL,
	PRIMARY KEY (STUDENT_ID),
	CONSTRAINT FK_STUDENT_GRADE FOREIGN KEY (GRADE_ID) REFERENCES grade (GRADE_ID),
	CONSTRAINT FK_STUDENT_ADDRESS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID)
);

