DROP SCHEMA IF EXISTS TEST;

CREATE SCHEMA TEST;

USE TEST;

DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS GRADE;
DROP TABLE IF EXISTS FEE;
DROP TABLE IF EXISTS CONTACT;
DROP TABLE IF EXISTS ENUMERATIONS;

CREATE TABLE GRADE(GRADE_ID INT(5) PRIMARY KEY, GRADE_NAME VARCHAR(255));

insert into grade (grade_id,grade_name) values (1,'PLAYGOURP');
insert into grade (grade_id,grade_name) values (2,'JUNIOR KG');
insert into grade (grade_id,grade_name) values (3,'SENIOR KG');
insert into grade (grade_id,grade_name) values (4,'FIRST');
insert into grade (grade_id,grade_name) values (5,'SECOND');
insert into grade (grade_id,grade_name) values (6,'THIRD');
insert into grade (grade_id,grade_name) values (7,'FOURTH');
insert into grade (grade_id,grade_name) values (8,'FIFTH');
insert into grade (grade_id,grade_name) values (9,'SIXTH');
insert into grade (grade_id,grade_name) values (10,'SEVENTH');
insert into grade (grade_id,grade_name) values (11,'EIGHTH');
insert into grade (grade_id,grade_name) values (12,'NINETH');
insert into grade (grade_id,grade_name) values (13,'TENTH');

CREATE TABLE ENUMERATIONS(
	ENUM_ID INT(5) PRIMARY KEY,
	ENUM_GROUP VARCHAR(256),
	ENUM_VALUE VARCHAR(256)
);

INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(1,'FEE_COMMENT','Tution Fee');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(2,'FEE_COMMENT','Celebration Fee');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(3,'FEE_COMMENT','Books Fee');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(4,'FEE_COMMENT','Dress Fee');

INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(30,'LECTURE_DAY','Monday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(31,'LECTURE_DAY','Tuesday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(32,'LECTURE_DAY','Wednesday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(33,'LECTURE_DAY','Thursday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(34,'LECTURE_DAY','Friday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(35,'LECTURE_DAY','Saturday');
INSERT INTO ENUMERATIONS(ENUM_ID,ENUM_GROUP,ENUM_VALUE) VALUES(36,'LECTURE_DAY','Sunday');

CREATE TABLE CONTACT(
	CONTACT_ID BIGINT(20) NOT NULL AUTO_INCREMENT,
	STUDENT_ID BIGINT(20),
	BUILDING VARCHAR(255),
	STREET VARCHAR(255),
	AREA VARCHAR(255),
	CITY VARCHAR(255),
	STATE VARCHAR(255),
	PRIMARY KEY (CONTACT_ID)
);

CREATE TABLE student (
	STUDENT_ID bigint(20) NOT NULL AUTO_INCREMENT,
	DATE_OF_BIRTH date DEFAULT NULL,
	FIRST_NAME varchar(255) NOT NULL,
	LAST_NAME varchar(255) DEFAULT NULL,
	MIDDLE_NAME varchar(255) DEFAULT NULL,
	GRADE_ID INT(20) DEFAULT NULL,
	CONTACT_ID BIGINT(20) DEFAULT NULL,
	PRIMARY KEY (STUDENT_ID)
);

CREATE TABLE FEE(
	FEE_ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
	STUDENT_ID BIGINT(20) NOT NULL,
	FEE DOUBLE(10,2),
	FEE_TYPE INT(4),
	COMMENT_TEXT VARCHAR(255) DEFAULT NULL
);

CREATE TABLE TIMETABLE(
	TT_ID INT(5) PRIMARY KEY AUTO_INCREMENT,
	GRADE_ID INT(5),
	SUBJECT VARCHAR(255),
	START_TIME DOUBLE(2,2),
	END_TIME DOUBLE(2,2),
	LECTURE_DAY INT(5),
	TEACHER_NAME VARCHAR(255)
);


-- SELECT * FROM TIMETABLE WHERE GRADE_ID=5 AND DAY='TUESDAY';

-- Constraints 

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_ADDRESS FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT(CONTACT_ID);
ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_GRADE FOREIGN KEY (GRADE_ID) REFERENCES grade (GRADE_ID);
ALTER TABLE CONTACT ADD CONSTRAINT FK_CONTACT_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);
ALTER TABLE FEE ADD CONSTRAINT FK_FEE_STUDENT FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID);
ALTER TABLE FEE ADD CONSTRAINT FK_FEE_ENUMERATIONS FOREIGN KEY (FEE_TYPE) REFERENCES ENUMERATIONS(ENUM_ID);
ALTER TABLE TIMETABLE ADD CONSTRAINT FK_TIMETABLE_ENUMERATIONS FOREIGN KEY (LECTURE_DAY) REFERENCES ENUMERATIONS(ENUM_ID);



